export const DEFAULT_POLLING_INTERVAL = 1000 * 60 * 1;

export const API_KEYS = {
  ALPHA_VANTAGE: process.env.NEXT_PUBLIC_ALPHA_VANTAGE_API_KEY,
  FINNHUB: process.env.NEXT_PUBLIC_FINNHUB_API_KEY,
  INDIAN_API: process.env.NEXT_PUBLIC_INDIAN_API_KEY,
};
